ipc = on
splash = false

# Carga una imagen ligera por defecto para el arranque
preload = /home/tu_usuario/.local/share/backgrounds/parasite-wallpaper/parasite-001.png
wallpaper = , /home/tu_usuario/.local/share/backgrounds/parasite-wallpaper/parasite-001.png
