general {
    # Bloquear inmediatamente si se presiona el botón de suspender
    lock_cmd = pidof hyprlock || hyprlock
    # Qué hacer antes de dormir (bloquear pantalla)
    before_sleep_cmd = loginctl lock-session
    # Qué hacer al despertar (encender pantalla)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Atenuar brillo tras 2.5 minutos (Opcional, requiere brightnessctl)
listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Bloquear pantalla tras 5 minutos
listener {
    timeout = 720
    on-timeout = loginctl lock-session
}

# 3. Apagar pantalla tras 5.5 minutos (ahorro de energía)
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspender PC tras 15 minutos
listener {
    timeout = 960
    on-timeout = systemctl suspend
}
