ipc = off
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/gerardo0/.local/share/backgrounds/big-sur-beach-timed/01.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/gerardo0/.local/share/backgrounds/big-sur-beach-timed/01.jpg
    fit_mode = cover
}
